security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        use_case_user_provider:
            id: App\Infrastructure\Symfony\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            lazy: true
            stateless: true
            custom_authenticators:
                - App\Infrastructure\Symfony\Security\ApiKeyAuthenticator
        client:
            lazy: true
            provider: use_case_user_provider
            form_login:
                login_path: client_login
                check_path: client_login
                enable_csrf: true
            logout:
                path: /logout
                target: client_login
            login_throttling:
                max_attempts: 5
                interval: '5 minutes'

    access_control:
        - { path: ^/u, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
