services:

  php:
    container_name: filesnap-php
    image: filesnap:3
    volumes:
      - ./docker_config/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    depends_on:
      - mariadb
    networks:
      - filesnap-network

  mariadb:
    image: mariadb:10.11.7
    container_name: filesnap-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - filesnap-network

  caddy:
    image: caddy:2.7.6
    container_name: filesnap-caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./:/var/www
    ports:
      - '80:80'
    networks:
      - filesnap-network
    depends_on:
      - php

volumes:
  mariadb_data:

networks:
  filesnap-network:
    driver: bridge
