parameters:
    app.environment: '%kernel.environment%'
    app.project_directory: '%kernel.project_dir%'
    app.public_directory: '%kernel.project_dir%/public'
    app.upload.relative_directory: '/user_uploads'
    app.upload.bytes_max_filesize: 50000000

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Application\Domain\Entity\User\Repository\UserRepositoryInterface: '@App\Infrastructure\Entity\User\Repository\MariadbUserRepository'
    App\Application\Domain\Entity\Snap\Repository\SnapRepositoryInterface: '@App\Infrastructure\Entity\Snap\Repository\MariadbSnapRepository'
    App\Application\Domain\Entity\Snap\FileStorage\FileStorageInterface: '@App\Infrastructure\Entity\Snap\FileStorage\LocalFileStorage'
    App\Application\Domain\Entity\User\Service\PasswordHasherInterface: '@App\Infrastructure\Entity\User\Service\SymfonyPasswordHasher'